[package]
name = "lev-automaton"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.1.1"
itertools = "0.14.0"

[dev-dependencies]
criterion = { version = "0.8.1" }
serde = { version = "1.0.219" }
serde_json = "1.0.143"

[[bench]]
name = "main_bench"
harness = false

